### ISSUE TITLE
Next Generation: Timebox

### ISSUE THREAD

**Issue by codingyourlife** [derHeinz/divoom-adapter#1]
Hey! This is not really an Issue but don't know how else to contact you...
This is the only code for the divoom LED device I found so far that could work on a Raspberry Pi. There is just one other Java inofficial Android app I found that might get running with enough effort but it's also for the old model. Did you try, does your adapter work on the Raspberry Pi?
There is a new generation called timebox instead of aura box and the price is just a little off. Do you know/think it's communicating similar/same? Do you plan on getting one and improving the project? I don't need the iOS/Android stuff but I would really need a programmable C# or Python API Interface! I'm not experienced with Bluetooth, hardware hacking and hardware in general so I don't know if I could do it on my own :-/

**Comment by ScR4tCh** [comment]
To advertise ;) : I created a CLI to control the Timebox. The protocol differs in some ways but is similar to the aurabox. Take a look here: https://github.com/ScR4tCh/timebox
