### ISSUE TITLE
Not Compatible with Divoom Pixoo?

### ISSUE THREAD

**Issue by qianmao** [derHeinz/divoom-adapter#11]
First, well done for the amazing work!

Is the protocol compatible with divoom pixoo? (http://www.divoom.com/product/pixoo.html).

I tried to run example.py and show-time.py against my divoom pixoo  but it didn't work. I can see the divoom pixoo showed a bluetooth icon then nothing happened. I guess this is because pixoo has different protocol than aurabox.

**Comment by derHeinz** [comment]
Sorry can't tell you this, I don't own this device. And as far as i know they don't publish their protocol details. Thus one needs to sniff the bluetooth connection an check whether it is at least similar or not.

**Comment by derHeinz** [comment]
Any updates on this device yet?

**Comment by qianmao** [comment]
Sorry I haven't got a chance to give it a try as I am not able to find an Android device for bluetooth sniffing. I am closing this for now. I will update this thread if I have some news.

**Comment by atmaniak** [comment]
Hi,
what do you need to sniff the bluetooth part ? i've just received my divoom pixoo and i'll be happy to help !

**Comment by derHeinz** [comment]
I would start creating HCI Snoop log on android device - this file can be read by wireshark. You can google how that works.

Now you would start using the original app and writing down the transferred bytes (commands) you captured via the hci snoop.
A very easy start is to write some code to repeat a command that you captured and know what it does. This hopefully yields the correct behavior on the pixoo.

If you repeat this process for several "commands" you'd probably get to know the protocol.
