### ISSUE TITLE
ditoo support?

### ISSUE THREAD

**Issue by AoNoAsgard** [derHeinz/divoom-adapter#13]
this is more a question then an issue.

i was trying to make it work for divoom ditoo but it seems that the data are different.

will it be supported or it's only for pixoo?

it would be fantastic if it could work.

**Comment by derHeinz** [comment]
sorry dunno about ditoo. It's for an old product called aurabox. However i know there are some people around that know how to communicate to the "timebox" thing. Check out https://github.com/ScR4tCh/timebox.
