### ISSUE TITLE
Support for Divoom Evo?

### ISSUE THREAD

**Issue by 53845714nF** [derHeinz/divoom-adapter#16]
Do you know if they support Divoom Timebox-Evo?

I get this:
```
bluetooth.btcommon.BluetoothError: [Errno 111] Connection refused
```

**Comment by derHeinz** [comment]
a sorry no idea - long since i worked on that particular project. Check the forks they may have support and working devices - and may be able to answer your question.

**Comment by 53845714nF** [comment]
ok but thanks anyway
