### ISSUE TITLE
What is expected in sys.argv[1] of example.py?

### ISSUE THREAD

**Issue by bigboss97** [derHeinz/divoom-adapter#4]
I tried to use the MAC address 11:75:58:0D:FF:FA of my Timebox. But it returns:
    self.sock = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
  File "C:\Users\bigboss\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bluetooth\msbt.py", line 43, in __init__
    self._sockfd = bt.socket (bt.SOCK_STREAM, bt.BTHPROTO_RFCOMM)
OSError: An address incompatible with the requested protocol was used.

**Comment by Badtz13** [comment]
You need to put the MAC address of the Bluetooth device that you want to connect to. To get a list of available Bluetooth devices, use the command `sudo hcitool lescan`

**Comment by bigboss97** [comment]
I tried it with my Timebox MAC address 11:75:58:0D:FF:FA and it said: An address incompatible...
I'm using Windows 7.

**Comment by Badtz13** [comment]
This repository uses bluepy a python library that doesn't run on windows. Are you using emulation to simulate a linux environment?

**Comment by derHeinz** [comment]
Sorry, @badtzmaru is totally right - it only works on linux due to bluepy.

**Comment by bigboss97** [comment]
I couldn't get the python scripts working on my Windows environment. So I decided to do it on Android with my own scripts instead  :-)
https://www.tapatalk.com/groups/rfobasic/bluetooth-speaker-timebox-control-t5425.html#p39130
