### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by ursfassler** [derHeinz/divoom-adapter#7]
Thanks for the provided information.
I like to provide some more information and change the code a bit. But I am missing the license of the project which makes it basically proprietary.

I would recommend GPL-3.0 as license.

**Comment by derHeinz** [comment]
Yeah right, I'm pretty new to licencing. Looked around a bit and added licence file for GPL-3.0 like you suggested.

**Comment by ursfassler** [comment]
Thanks, that is great!
